### ISSUE TITLE
Bump up stack LTS resolver version

### ISSUE THREAD

**Issue by chshersh** [y-taka-23/miso-tutorial-app#2]
`lts-6.30` is too old... Would be great to bump up LTS version so project could be build with GHC-8.2.2 at least. You can also keep old `stack.yaml` with name `stack-7.10.3.yaml` name.

**Comment by y-taka-23** [comment]
Yap, it's just because the official MIso samples use the older version of LTS. I'm gonna try bumping the version uo.

**Comment by y-taka-23** [comment]
I bumped the version up to `lts-7.19` at 6dc846336334867708a4d591d1d8efb677fa7d46. It's still a bit old I know but the newest version in officially provided examples of GHCJS and Miso, e.g.

https://github.com/dmjio/miso/blob/b30314608ce371f259fc21a93eaf5a8116e1392d/stack/ghcjs801/stack.yaml

If you have passion to upgrade the app to the latest LTS, feel free to send a PR.
