### ISSUE TITLE
Feature Request: Precompiled Docker Image

### ISSUE THREAD

**Issue by madnight** [y-taka-23/miso-tutorial-app#3]
Compiling the simple example app takes ages.  
It would be nice and much more beginner friendly if the app could be started within minutes.  

Instead of docker i could also think of a nix build that fetches precompiled binaries.

**Comment by y-taka-23** [comment]
Yap, sounds good. Actually I have a plan to implement the server-side by Servant (instead of the current webpack-dev-server) to demonstrate Miso's isomorphic feature, so the containerization might be better to postpone until that.

**Comment by madnight** [comment]
Thx, your multi-stage Dockerfile and ready to fire up `ytaka23/miso-tutorial-app` docker image is absolutely great.
